apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-t1
  labels:
    app: nginx2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: ahkworld/nodejs-t:main
        ports:
        - containerPort: 8888

